### ISSUE TITLE
Implement a CARv2 SelectiveCARAPI when clients have upgraded to go-ipld-prime v0.9.0

### ISSUE THREAD

**Issue by aarshkshah1992** [ipld/go-car#104]
https://github.com/ipld/go-car/pull/102 removes the CARv1 dependency from the WIP CARv2 library  and states the motivation for doing so i.e. to not force clients to upgrade to the breaking `go-ipld-prime v0.9.0` release because the latest CARv1 release depends on `go-ipld-prime v0.9.0`.

Towards that goal, the CARv2 library also holds back from implementing a `SelectiveCAR` API for v2 as the `SelectiveCAR` implementation would need `go-ipld-prime` and we should be using the latest ipld prime release i.e. `go-ipld-prime v0.9.0` to implement it rather than using an older IPLD prime release.

This issue is meant to capture the fact that we should implementing a CARv2 `SelectiveCAR` API when clients have upgraded to `go-ipld-prime v0.9.0`.

**Comment by masih** [comment]
Fixed by https://github.com/ipld/go-car/pull/269
