### ISSUE TITLE
v2: consider adding logging options

### ISSUE THREAD

**Issue by mvdan** [ipld/go-car#112]
For example:

```
func WithLogging(func(format string, args ...interface{})) Option
```

See https://github.com/ipld/go-car/pull/111#discussion_r659582951. There are a few places where we can't easily return errors, such as AllKeysChan's inner goroutine, so it's a shame if the best we can do is simply throw them away.

cc @dirkmc

**Comment by mvdan** [comment]
Removing from the milestone for now; we agreed this is not a pressing need for Ignite, and it can always be added later.

**Comment by mvdan** [comment]
After talking to Masih, we agreed that opt-in logging is still good, but error reporting via per-blockstore logging isn't great. So errors from AllKeysChan is now https://github.com/ipld/go-car/issues/177.

**Comment by BigLep** [comment]
Good idea.  Closing for now since no usecase is driving this.  We can reopen if/when that's the case.
