### ISSUE TITLE
blockstore: improve file handling by OpenReadOnly

### ISSUE THREAD

**Issue by mvdan** [ipld/go-car#120]
See https://github.com/ipld/go-car/pull/110/files/4eac6e2bf70403064cb9620a14225e3592201418#r659729739.

**Comment by masih** [comment]
As per #137, more specifically https://github.com/ipld/go-car/pull/137/commits/71bc303b4ce78eea0e44a1537332933b8e3c9e0d `ReadOnly` blockstore API will no longer modify the path given. Instead, a user is encouraged to use `index.Generate` and `index.Attach` to modify an index-less CAR file, may it be v1 or v2.
