### ISSUE TITLE
decide what the blockstore semantics should be before tagging a stable release

### ISSUE THREAD

**Issue by mvdan** [ipld/go-car#130]
There's a [Slack thread](https://protocollabs.slack.com/archives/C01MFLTLKTP/p1625142319426200?thread_ts=1624963667.404300&cid=C01MFLTLKTP) going into how CARv2's blockstore should behave.

Whatever we agree to in there, we should reflect it in the code.

Also worth noting that the current default behavior is somewhat inconsistent: just like go-ipfs, "Has" reports matches by multihash. But unlike go-ipfs, Put doesn't deduplicate by hash, and AllKeysChan doesn't flatten CIDs to use the "raw" codec.

**Comment by willscott** [comment]
I think i'd look towards @aschmahmann for suggestions as to expected blockstore semantics in this regard

**Comment by mvdan** [comment]
Yep indeed, I think we can continue using the Slack thread for now. This is more of a reminder for the milestone than anything.

**Comment by mvdan** [comment]
It seems like we're agreeing that there will be a separate blockstore v2 interface, based on multihashes instead of CIDs. We'll want to implement both the existing CID-based interface, as well as the new multihash-based one.

The implementation new one will definitely just use multihashes by definition. The implementation of the old one might do the safe thing of using whole CIDs, similar to what the current wip-v2 branch does.

**Comment by mvdan** [comment]
API done in https://github.com/ipld/go-car/pull/166, but the implementation of CID vs multihash identity is a TODO.
