### ISSUE TITLE
add opt-in support for treating null padding as EOF in v2

### ISSUE THREAD

**Issue by mvdan** [ipld/go-car#142]
See https://github.com/ipld/go-car/issues/140#issuecomment-874522993.

Some downstreams did this via https://github.com/ipld/go-car/commit/11b6074b6d4d6b175e42d24003c1ecacbc48917a, which never made it to master. We should add it to v1 and do a tag, but in a way that is opt-in, to ensure backwards compatibility.

**Comment by masih** [comment]
Note, carv2 forks the v1 due to dependency issues in dependant projects outlined in https://github.com/ipld/go-car/issues/104. The option needs to also be added in v2 with default setting to error on null padding.

**Comment by mvdan** [comment]
I've repurposed this issue to be for v2, and v1 is now https://github.com/ipld/go-car/issues/171.

**Comment by mvdan** [comment]
Done in https://github.com/ipld/go-car/pull/166.
