### ISSUE TITLE
Client should be able to get a detached Index from a CARv1 or CARv2 file

### ISSUE THREAD

**Issue by aarshkshah1992** [ipld/go-car#143]
Currently, if a client wants to to generate/get just the Index for a given CAR file, the client needs to write a lot of boilerplate, especially if the client dosen't know whether what it has is a CARv1 or an indexed CARv2. We don't need this feature for UnIndexed CARv2s and leave it for you guys to decide if you want to support that too for now.

```
Assume reader here is an `io.ReadSeeker` and we don't know whether the stream is a CARv1 or a CARv2:

	// determine CAR version and Index accordingly.
	ver, err := car.ReadVersion(reader)
	if err != nil {
		return
	}
	// seek to start of file as reading the version above will change the offset.
	if _, err := reader.Seek(0, io.SeekStart); err != nil {
		return
	}
	
	var idx carindex.Index
	switch ver {
	case 2:
		carreader, err := car.NewReader(reader)
		if err != nil {
			return
		}
		if has := carreader.Header.HasIndex(); !has {
			return
		}
		idx, err = carindex.ReadFrom(carreader.IndexReader())
		if err !=  nil {
			return
		}
	case 1:
		cidx,err  := carindex.Generate(reader)
		if err != nil {
			return
		}
		idx = cidx
```

It would be great to have an API that takes either a CARv1/v2 stream and can generate/detach the Index from it and return it.

**Comment by masih** [comment]
Fixed in #144 by adding `ReadOrGenerateIndex(rs io.ReadSeeker) (index.Index, error)` that accepts both v1 and v2 payload,  generating index if it is not present.
