### ISSUE TITLE
CARv2 blockstore throws "cannot resume from a finalized file"

### ISSUE THREAD

**Issue by aarshkshah1992** [ipld/go-car#155]
After integrating the CARv2 blockstore resumption changes, one of our test fails with the following error:

_"cannot resume from a finalized file"_.

Unfortunately, this is a valid edge case we need to support to support restarts of Filecoin data transfers. Here's the scenario:

1. Storage client transfers a 64Gib file to to the Storage Provider.
2. Storage provider writes the CARv2 file to a  blockstore -> calls `Finalize` but dosen't persist the fact that it's finalized. 
3. Storage provider restarts and attempts to create a CARv2 blockstore from the CARv2 file it has and then finalizes it.

**Comment by masih** [comment]
Fixed by #156
