### ISSUE TITLE
Improve resumption from files with unknown CARv1 payload size

### ISSUE THREAD

**Issue by masih** [ipld/go-car#157]
this is unfortunate that partial writes that close uncleanly are now going to be something we aren't comfortable resuming.

It seems more likely that this is a case where the index has not been written at all, right?
It may be worth doing the slower recovery:
* Scan through the blocks in the carV1
* For each, see if the length is valid with regards to the length of the file
* either re-hash each block and make sure the contents match the CID, or ideally build up the index while doing the scan of lengths, and then do that hashing backwards until you find a valid block.
* if there is content after the last valid block, and it parses as an index, great
* if there is at most 1 final invalid block, we crashed in the middle of writing it and can truncate to before that and resume.
* otherwise we have an actual corrupt car and should force a new full export.

_Originally posted by @willscott in https://github.com/ipld/go-car/pull/156#discussion_r669728518_

**Comment by BigLep** [comment]
Good to note.  There hasn't been a user driving this usecase yet.  We can reopen if/when that changes.
