### ISSUE TITLE
add opt-in support for treating null padding as EOF in v0 (CARv1)

### ISSUE THREAD

**Issue by mvdan** [ipld/go-car#171]
https://github.com/ipld/go-car/issues/142 is about the v2 module, so this issue is about also propagating the feature to the v0 module, as per https://github.com/ipld/go-car/issues/140#issuecomment-874522993.

**Comment by masih** [comment]
Note, util functions in v1 are exported and used it seems:
* https://grep.app/search?q=go-car/util&filter[lang][0]=Go
* https://grep.app/search?q=go-car/util

**Comment by mvdan** [comment]
This is not urgent, as the only need for this is Filecoin, and they can't upgrade to go-car v0 master until the ipld-prime upgrade via graphsync takes place.

**Comment by rvagg** [comment]
closing this out as we've largely migrated lotus away from direct CARv1 usage and this isn't needed there anymore (as far as I recall anyway)

someone's welcome to reopen if they believe this is important but we'd like to keep CARv1 stable/in-stasis as much as possible now
