### ISSUE TITLE
CARv2 TestBlockstore fails intermittently

### ISSUE THREAD

**Issue by masih** [ipld/go-car#175]
Happened on Windows CI build [here](https://github.com/ipld/go-car/runs/3086058640?check_suite_focus=true). 

```
      readwrite_test.go:111: AllKeysChan returned an unexpected amount of keys; expected 1049 but got 0
123
```

**Comment by mvdan** [comment]
This might be a race with closing the channel before it's fully read.

**Comment by masih** [comment]
This can also be the context with timeout of 1 seconds passed to `AllKeysChan`. The one second timeout may be aggressive if the CI running the tests is under heavy load.

**Comment by mvdan** [comment]
> This might be a race with closing the channel before it's fully read.

To clarify: the race is that we use a buffering of 5, but we close as soon as we've sent all keys to the channel - which might be before the receiver has consumed them all. We should remove the buffering to get rid of the race.
