### ISSUE TITLE
ensure that writing DAGs backed by an ipld-prime BlockReadOpener is easy

### ISSUE THREAD

**Issue by mvdan** [ipld/go-car#197]
Right now it's hard with v0; it requires duct taping interfaces, such as:

```
type readStore ipld.BlockReadOpener

func (rs readStore) Get(c cid.Cid) (blocks.Block, error) {
        link := cidlink.Link{Cid: c}
        r, err := rs(ipld.LinkContext{}, link)
        if err != nil {
                return nil, err
        }
        data, err := ioutil.ReadAll(r)
        if err != nil {
                return nil, err
        }
        return blocks.NewBlockWithCid(data, c)
}

func toReadStore(opener ipld.BlockReadOpener) car.ReadStore { 
        return readStore(opener)
}
```

This is because v0 wants a Get method similar to a Blockstore (https://pkg.go.dev/github.com/ipld/go-car#NewSelectiveCar), but blocks stored and linkified by ipld-prime are inside a https://pkg.go.dev/github.com/ipld/go-ipld-prime#BlockReadOpener. The two serve largely the same purpose, but the interfaces are slightly different.

If we want to continue maintaining v0 in the long term, that `toReadStore` helper should probably be exposed as part of its API.

v2 doesn't have this problem yet, as it had to give up anything similar to v0's selective car writer. When it does, we should also make sure it's easy to give it both a BlockReadOpener as well as a ReadStore.

**Comment by BigLep** [comment]
Closing since this applies to go-car v0 and we're not investing more there.
