### ISSUE TITLE
efficient buffer-less ExtractV1File method

### ISSUE THREAD

**Issue by raulk** [ipld/go-car#207]
CARv2 embeds a CARv1 fully, including its header. It should be possible thus to unpack a CARv1 from a CARv2 file efficiently by `os.Truncate`ing at the end, and `io.Copy`ing through `*os.File` descriptors to allow Go to delegate to the kernel instead of performing the copy in user land.

Two use cases are requested:
1. Extract inner CARv1 into a new file.
2. Overwrite existing CARv2 with the CARv1 contents (potentially by opening two `*os.File` file descriptors against the same file, seeking in the source descriptor to the right offset, and performing `io.Copy`?).

**Comment by mvdan** [comment]
On Slack I think there was agreement to call this `ExtractV1File`, to mirror `WrapV1File`.

We would not need a mirror for `WrapV1` with io interfaces, because the whole point of this API is OS+filesystem efficiency.

**Comment by raulk** [comment]
Request: whoever adds this capability, please go back and adopt it in Lotus: https://github.com/filecoin-project/lotus/pull/6671#discussion_r685909972.
