### ISSUE TITLE
`IndexSorted` should not load CIDs with multihash code of `IDENTITY`

### ISSUE THREAD

**Issue by masih** [ipld/go-car#215]
It is possible for a CAR file to contain CIDs with multihash `IDENTITY`. Such CIDs could significantly bloat the index size and cause OOM error. As stated in the [CARv2 spec](https://ipld.io/specs/transport/car/carv2/#index-format) Index should disallow them and safely skip over them when indexing a CAR file.

`IndexSorted` currently loads all given CIDs. Skip over CIDs with multihash `IDENTITY`.

**Comment by rvagg** [comment]
Indeedy, we even included this in the [spec](https://ipld.io/specs/transport/car/carv2/#index-format) and made it bold:

> Indexes **should not include identity hash CIDs**. It is assumed that any use of a CARv2 as a blockstore will return identity CID data immediately by extracting it from the CID, therefore there should be no need to provide indexing for such entries.

**Comment by masih** [comment]
The new index type does this already; I'll get this sorted in the `IndexSorted` type shortly
