### ISSUE TITLE
move repo to IPLD org

### ISSUE THREAD

**Issue by mikeal** [ipld/go-car#22]
The spec is being maintained in the IPLD project as well as some other tools and implementations.

**Comment by hannahhoward** [comment]
keep in mind links are in use across the filecoin project -- we should probably coordinate this.

**Comment by mikeal** [comment]
GitHub creates forwards for all the links, including the git remote url, so it shouldn’t cause any breaks or disruption.

**Comment by Stebalien** [comment]
@mikeal it will due to how go modules work. Really, instead of _moving_, we should probably _fork_ then make this repo a shim that depends on the new one.

**Comment by Stebalien** [comment]
(or we can move and make sure to handle the fallout)

**Comment by mikeal** [comment]
we should still just move it, dependencies are likely to grow and maintaining it across two repos will only get more difficult in the future. the early we deal with the migration the better.

**Comment by Stebalien** [comment]
Really, _forking_ and archiving is probably the least problematic approach. Users can upgrade and switch when ready.

**Comment by ribasushi** [comment]
@Stebalien has this been decided? Since I will be pushing a PR soon for https://github.com/ipfs/go-ipfs/issues/6870 this is somewhat pressing...

**Comment by Stebalien** [comment]
Just use this repo for now.

**Comment by Stebalien** [comment]
Nvm. I've moved this and re-forked it back to the IPFS repo so we don't break upstream.
