### ISSUE TITLE
blockstore: ReadOnly.AllKeysChan should be able to use the index in some cases

### ISSUE THREAD

**Issue by mvdan** [ipld/go-car#242]
I believe that if a CAR file has a MultihashIndexSorted index, and has the "fully indexed" characteristic bit, and UseWholeCIDs isn't turned on, then we could implement AllKeysChan with just the index, without having to seek through the entire inner CARv1. Because all we need is to loop over all the multihashes, including duplicates and identity CIDs, and the index contains those in the scenario laid out above.

Purely a special case optimization though. The reason I was thinking about this was in the context of the indexer provider for CARs; we will be using the index directly, so we don't strictly need this optimization, but it would be nice for blockstore users to get the optimization too.

cc @masih @willscott in case I'm missing something here.

**Comment by masih** [comment]
Good point; I do however wonder could we supply a channel of CIDs from multihashes? 

The `MultihashIndexSorted` carries no information about codec. Going back to the loos specification on blockstore API, one could argue `AllKeysChan` based on it cannot supply a channel of CIDs _as they occur in CAR_.

**Comment by mvdan** [comment]
If UseWholeCIDs is off (as per default), then the blockstore operates purely on multihashes, and this means AllKeysChan always returns "raw" multicodecs.

**Comment by masih** [comment]
Ah so do we explicitly mention that `AllKeysChan` will supply CIDs with `Raw` codec if that option is enabled? I thought what that option means is that only _multihash_ portion is used for comparison.

**Comment by mvdan** [comment]
From the UseWholeCIDs docs:

> • AllKeysChan will return the original whole CIDs, instead of with their multicodec set to "raw" to just provide multihashes.

**Comment by mvdan** [comment]
And yup, this matches what go-blockstore does; the new "just multihashes" method sets multicodecs to Raw in AllKeysChan. So it's also consistent across its methods.

**Comment by masih** [comment]
Perfect thank you 🍻
