### ISSUE TITLE
feat: reversed creator friendly CARs ?

### ISSUE THREAD

**Issue by Jorropo** [ipld/go-car#270]
Because I belive this will be clearer, let me start with a diagram:
![Untitled Diagram](https://user-images.githubusercontent.com/24391983/144733196-14303ecf-32e2-4041-80b1-bb647f7d8218.png)

Current CARv1 archives are `header | roots | files` generally.
This is helpfull for unpackers of the archive because that mean they can just stream the CAR in and create relevent directories and file as they see it.
However I want to do the reverse, I want to pipeline the creation of a car archive (note I do mean creating everything so chunking and layout while it's being streamed, note just reading from a blockstore and exporting).

The reason to do so is that I have an IPFS pinning service which accepts CAR archives and I have a really low ressources node that host data, I want to stream data from my archive node to the pinning service (and a pipeline is the best way to do with the minimal footprint).

The current system require me to first chunk and layout everything before I can even start streaming my CARs because the first bytes of the CAR include the root CID which I only learn after having done all the chunking / layout work.

A reversed CAR would not be pipelinable while unpacking since you would first learn about files then learn about the directories that contain thoses files but I don't think that an issue as long as we have both options, I mainly just want to ingest thoses blocks into a blockstore which would not be impacted by this.

**Comment by willscott** [comment]
You can to some extent do this using the current car format.

The only thing in the header, as you note, that means you'd need to have walked the dag before streaming is the root CID. This isn't something you need to be valid for your syncing use-case.

Instead make a car with the roots set to empty and then the stream of blocks from your sync.
Then afterwards communicate the CID(s) that need to be explicitly pinned.

I think the work that would enable your use case is that you want something like the current [`blockstore.OpenReadWrite`](https://github.com/ipld/go-car/blob/master/v2/blockstore/readwrite.go#L89), but in a `OpenAppendOnly` configuration that writes to a stream and doesn't track an index.

**Comment by Jorropo** [comment]
> Then afterwards communicate the CID(s) that need to be explicitly pinned.

That requires me to write more OOB code than I want.

After writing some CAR encoding code myself I can know make a proposal :

# Proposal

A repeat of the goals, this is a version of CAR that would allow creation to ingest pipelined code.
That mean you must be able to on a FiFo stream write the CAR file while you are chunking and layouting the blocks with minimal

First start with the usual CBOR encoded version + roots header, if the version code of the leading header is 3 (note this version would be named `CARvR` not CARv3) then read as CAR-reversed and ignore the root buffer.
Then a similar `length | block | cid` patern would be used:
```
Signed varint (contain length of block blob excluding CID) | block blob | block's CID without 0x00 indentity multibase (or what we call "binary CID")
```
First assume that the length is positive, I'll go over if it's negative after.

So this is basically an item of the car, you first read the varint, check it's positive, then read the block buffer then read the CID.
Things to note :
- the CID is placed after the block, that is for optimal pipelining of block, if the CID were to be placed first we would need to read the block twice once when you hash it to get the CID, write the CID and then reread the block when you actually stream it (you could also keep the block in memory but that bad pipeline practice when you can avoid to do so). This allows to write code like that :
```go
io.CopyN(outFiFo, io.TeeReader(inputFiFo, hashingWriter), blockSize)
// This code read the inputFiFo once with one buffer and share it to both the hashing function for the CID and the output FiFo
```
- you can see that unlike CARv1 the first length isn't the length of the item (block + CID) but the length of the block, that means to get the next item you must read the CID too to get it's length, that is intentional, this is to future proof us against variable length hashing functions, since we want to hash while we send the block in a pipeline manner we don't know yet what the CID is while we are writing the block, this allows us to write the CID length using CID's builtin variable length system only after we hashed the block.

Then we can stack as much items back to back as you want, adding blocks as you need.

## Negative size ?

If the size of a block is negative that means it's not a block but a roots buffer.

Then you do classical `~size + 1` twos complement sign flip and recover the true size. In this case size is the number of roots, roots are just binary CIDs (without identity multibase) that you can read back to back.

## 0 size

If the size is zero that signals end of car, note it is allowed to omit the 0 size token and use `io.EOF` instead.

The reason to do that like that rather than use `io.EOF` is that if you want to pipeline a CAR into an other stream you can't just put your car size in front of your car because it doesn't exists yet and you can't close the connection to signal that your car is finished because you intend to continue to use this connection.

# Sumary

## Header

If the CAR header version is 3 that mean reversed CAR.

## Decode loop

Read varint `size`.

If `size` is
- `== 0` end of car, break out of decode loop
- `> 0` decode block (see `Decode Block summary`)
- `< 0` decode roots (see `Decode Roots summary`)

### Decode block

Read `size` amount of bytes, thoses are the blob content of your block.
Read a binary CID using CID's variable length specs (note thoses are binary CIDs not identity multibases).

Do with this CID + block whatever you need to do (yield to a generator, add to a blockstore, ...)

### Decode roots

Repeat this `-size` amount of time (since `size` is negative, flip it positive) :
- Read a binary CID using CID's variable length specs (note thoses are binary CIDs not identity multibases) and add this CID to the roots list.

# Stylised example :

```
[CAR Header: {version: 3, roots: [] }] |
[Item (block): { varint = 123456 | 123456 bytes long content buffer | CID of that block (Qmbar) }] |
[Item (block): { varint = 2000 | 2000 bytes long content buffer | CID of that block (Qmfoo) }] |
[Item (root): { varint = -2 | [2 CID long list: {CID of first root (Qmbar) | CID of second root (Qmfoo)} ] }] |
[Item (block): { varint = 3000 | 3000 bytes long content buffer | CID of that block (Qmeee) }] |
[Item (block): { varint = 3000 | 3000 bytes long content buffer | CID of that block (Qmaaa) }] |
[Item (root): { varint = -1 | [1 CID long list: {CID of third root (Qmaaa)} ] }] |
[Item (end): {varint = 0}] |
EOF
```

**Comment by willscott** [comment]
## For car header / version detection

Rather than a 'version 3', we could signal this by reserving one of the bits in the [characteristics](https://ipld.io/specs/transport/car/carv2/#characteristics) field of the car v2 header.

## For the negative size block

The downside to this approach is that you only can learn about the root at the end of importing all of the blocks. It would be good to have a scheme where the presence of a signalling flag in the header means that the reader can seek to the end of the file, and know where to read the root. Being able to learn that efficiently seems useful, but maybe you can explain a bit more about if these streamed car files are going to stick around, or will stream once and never be used again.

**Comment by Jorropo** [comment]
> Rather than a 'version 3', we could signal this by reserving one of the bits in the characteristics field of the car v2 header.

Yes maybe, I'll take a look.

> The downside to this approach is that you only can learn about the root at the end of importing all of the blocks.

I've basically write this assuming the creator of the CAR knows the least infos itself.
The way I intend to use this I don't even know if a block is a root while I'm streaming it (basically I just keep streaming until reaching ~32Gigs and the top most blocks that aren't linked by anything else are my roots, that so my pinning service can build filecoin pieceIDs).

This would have atrocious performance if you just have the whole file and want to read part of it, however I don't expects anyone to use this outside of a streaming context (maybe it should even be renamed `CAR-stream`).
If you correctly use this the receiver would also pipeline adding blocks to his datastore while his is receiving the stream so this would be IO bound anyway.

> It would be good to have a scheme where the presence of a signalling flag in the header means that the reader can seek to the end of the file

How do you do that ?
The most simple way I can think of doing this is to have in the header an offset to the root items, which I don't know because my goal is to be fully FiFo compatible and I don't know my car length while I'm sending the header because my chunks and layout doesn't even exists yet.

An other way would be to say that a CARvR always finish by the roots (because right now it's valid to put them in whatever order in the item stream), then for a stream you need to read all of it however if you have random access capabilities (ie, on-disk), your can seek to the end and read it backward (imagine encoding an offset from the end of the file at the end of the file).

**Comment by willscott** [comment]
The CARv2 spec optionally supports an index, but you don't need to include it. It does have the flexibility that you can define your different behavior within the v2 format though.

I haven't fully thought this through, but i could imagine you do something like:
* if characterics 'trailer set' bit is set, then:
* Seek to end of file if file,
* Last 40 bytes are attempted to be parsed into a 'trailer' struct object
* if that succeeds, i now know the length and root CID of the car, and can use that to use the car file for (for example) traversals /graphsync / incrementally-verifiable transfer purposes.

In terms of layout, it would look like
`<car v2 header> | <car v1 header no roots> | block | block ...  | block | 0 block | trailer block`
where trailer block would be
`length | <cid with codec in the private range at an agreed codec of 'car-trailer'> | cbor-encoded trailer struct`

**Comment by Jorropo** [comment]
So just FYI all of this isn't needed for my use case. And even tho that interesting to think about I just need to stream block.

But let's assume we also want good random access or good unpacking if the file is stored on disk.

# V2 index ?

We could something like this :
```
<car v2 header> | <car v1 header no roots> | block | block ... | block | 0 block | <car v2 index> | magic trailer block (relative offset to start of index)
```

Then instead of being atrocious perfs for someone unpacking the car into the directory structure would have good performance but only if the file is stored on disk.

Imagine something like this :
```
carReversedPipeline | tee backup.car | curl --data-binary @- https://example.com/api
```
If the v2 index where to be added at the end the `backup.car` file would actually be decent to read.

To me that fine I just need to collect blocks CIDs and offsets and dump them in the index while to a reader they just seek to the end read the offset seek again and then start decoding the v2 index.

However this require to generate v2 indexes which I don't know if that worth my time coding.

# Backward V1 ?

A simpler tradeoff that would make CARvR at least as good as CARv1 on disks is to have relative offsets to the start of the item at the end of the item.
Like this :
```
<varint block length> | <block blob> | <cid> | <uint64 -offset to start of block length>
```
(note the `-offset` is uint64 because reading varints backward is non trivial (if you can do it at all ?), so then it makes it much simpler, you just read `8` bytes to know the offset)

Then if you have `backup.car` and want to unpack it, you can seek to the end read the offset, read the block and CID and repeat (and your blocks would be in normal order first getting directories then files inside thoses directory).

**Comment by BigLep** [comment]
2022-01-07 discussion: @mvdan will read the thread and suggest next steps.  Also Ccing @masih per Daniel's suggestion.

**Comment by rvagg** [comment]
@Jorropo I'm going to close this to get it off the board but if you think that's premature then feel free to reopen. The way forward I _think_ appropriate for this is:

1. Open an issue in ipld/ipld to spec out a new CAR version _or_ an amendment to the existing one (CARv2 has some extensibility points and that would be welcome too)
2. Open up a draft PR here that demonstrates changes here that don't break existing use-cases or spec.
