### ISSUE TITLE
`car.SelectiveCar.Write` doesn't forward the context to the traverser

### ISSUE THREAD

**Issue by Jorropo** [ipld/go-car#315]

**Comment by rvagg** [comment]
I'm not sure exactly what this is referring to, I suspect it's a non-issue and I'd like to close it if it is.  go-car (v0)'s `SelectiveCar#Write` calls to `SelectiveCar#traverse` which creates a `selectiveCarTraverser` with a reference back to the `SelectiveCar` instance. Then in `selectiveCarTraverser#traverseBlocks` it uses the `ctx` from the parent `SelectiveCar` for both `ipld.LinkContext` and `traversal.Config`. So, when you `NewSelectiveCar` with a `Context`, it should go all the way down into the traverser.

If I'm missing something here and fixing it would mean breaking the API for go-car v0 by adding an argument then I think we might have to skip it anyway and just encourage go-car/v2 usage instead. We've taken a fairly firm stance on avoiding making changes to v0 where they aren't security fixes.

**Comment by Jorropo** [comment]
I know this description is bad.
There is no way for a consumer to provide a context that (maybe wrapped) will be used for get requests.
This mean we have code like this in Kubo:

https://github.com/ipfs/kubo/blob/d2c49278f6e215ef37f2c6e0e5a847516b3d3ce7/core/commands/dag/export.go#L137-L145

I know what I need to do, I'll send a PR once I get some time, it should be small and obviously correct change once you see the fix.

**Comment by BigLep** [comment]
@Jorropo : what's the priority of this.  Are you still planning to take this on?

**Comment by rvagg** [comment]
Counterpoint: we should mess with the v0 API as much as possible, we have v2 for a reason. That whole block @ https://github.com/ipfs/kubo/blob/d2c49278f6e215ef37f2c6e0e5a847516b3d3ce7/core/commands/dag/export.go#L49-L55 should just be using go-car/v2. There's a [`TraverseV1`](https://pkg.go.dev/github.com/ipld/go-car/v2#TraverseV1) call just for this case and if it's not ideal in some way then we should address it there.
