### ISSUE TITLE
[issue] go get -u https://github.com/ipld/go-car

### ISSUE THREAD

**Issue by angelorc** [ipld/go-car#33]
Hi guys I tryed to get go-car and I'm in stuck with this.

# Cmd
```
go get -u https://github.com/ipld/go-car
```

# Error
```
../../work/pkg/mod/github.com/ipld/go-car@v0.1.0/selectivecar.go:14:2: module github.com/ipld/go-ipld-prime@latest found (v0.0.3), but does not contain package github.com/ipld/go-ipld-prime/impl/free
```

**Comment by mvdan** [comment]
You shouldn't use `-u` when adding module dependencies, as that will update transitive dependencies and something might break. If `go get -d github.com/ipld/go-car` fails, please let us know.
