### ISSUE TITLE
Limit definitions

### ISSUE THREAD

**Issue by wackazong** [ipld/go-car#511]
I am working on a Rust implementation of a car utility. Could you help me shed some light on where go-car limits are defined?

- Maximum raw section size (256 * 1024 bytes)
- Maximum number of links in a dag-pb (174 is the number I see in the created .car files)

Thanks!

**Comment by willscott** [comment]
Neither of these are limits specific to car as a file format, but are rather limits in `unixfs` - the encoding of file into blocks.

https://github.com/ipfs/go-unixfsnode/blob/main/data/builder/file.go#L299-L323 is probably a rough answer to your question

**Comment by wackazong** [comment]
Great, thanks. That will do.
