### ISSUE TITLE
disable Travis

### ISSUE THREAD

**Issue by marten-seemann** [ipld/go-car#53]
This repository is using the unified Go testing / checking workflow. We should disable Travis (and delete `.travis.yml`).
I don't have permission to edit CI settings. @Stebalien, do you?

**Comment by mvdan** [comment]
As far as I can tell Travis isn't running anymore, or at least isn't showing up in the CI reports on master commits. The travis.yml file was deleted.

**Comment by marten-seemann** [comment]
Thanks for the ping. You're right, this issue was resolved at some point.
