### ISSUE TITLE
CAR v2 characteristics should indicate if index is included

### ISSUE THREAD

**Issue by masih** [ipld/go-car#83]
We want to be lazy about generating an index. This is so that if we've already got the carv2 header at the beginning of the car, we can write an index suffix without relocating the actual car data on disk.

**Comment by rvagg** [comment]
I can't recall if/where we discussed this but I think having an "index offset" in the header of `0` should do this for us without having to use the characteristics bitfield. It can be overwritten later if needed since it's in a fixed location and `0` is a good indicator of "not present".

**Comment by masih** [comment]
Agreed, thanks @rvagg  The body of this issue was copied from slack conversations with folks. Closing.
