### ISSUE TITLE
Consider supporting multihash in CAR v2 Blockstore

### ISSUE THREAD

**Issue by masih** [ipld/go-car#93]
The CARv2 index is queryable by CID exposed via `Blockstore` API. That API as used in Filecoin is [multihash based](https://github.com/ipfs/go-ipfs-blockstore/blob/2e485bebeebac8bdc0d000c5115265368e25d710/blockstore.go#L134-L139 ). 

It would be useful if the blockstore API implemented by CAR v2, backed by the index, can be queryable by multihash.

Questions:
* When we `Get` a block should it be the CID as it was encoded in the CAR, or in the format it was requested?
   - The format it was requested makes sense.
   
* What format should the keys be in when `AllKeysChan` is called?
  - Probably the format encoded in CAR?
  - Could defaulting to V1 cause problems?

**Comment by mvdan** [comment]
> It would be useful if the blockstore API implemented by CAR v2, backed by the index, can be queryable by multihash.

Done in 2a8db361715d59a52ba19bd393c8111689e2f5d3. The blockstore interface assumes that block uniqueness should be defined by the CID's hash, i.e. `someCid.Hash()`.

>     * The format it was requested makes sense.

This is already how it works, and I agree it's what makes the most sense. It also seems to be how everyone agrees the blockstore Gets work.

>     * Probably the format encoded in CAR?

I think so. I don't think we can "convert" all the CIDs to CIDv1 and assume clients won't break. Enforcing CIDv1 could also be problematic if we ever move towards a CIDv2.

I think what the current AllKeysChan does is correct, so I'm going to close this issue for now. There's an optimization we could do with using the index when walking, but that shouldn't affect the behavior of the API.
