### ISSUE TITLE
Read/Write blockstore should support resuming 

### ISSUE THREAD

**Issue by masih** [ipld/go-car#98]
When writing to a blockstore, the write might fail before the blockstore writes are "finalised/flushed". The API should support resuming writes, picking up where it left off. 

This is a _must_ for Ignite requirements.

**Comment by willscott** [comment]
while each put should ensure the block is durable, we can assume that the need to resume is *rare* in comparison to the writes, so it is likely an acceptable tradeoff to not serialize the index until finalization, and instead re-generate the partial index of what has been written so far on resumption

**Comment by raulk** [comment]
For the sake of completeness, another possibility would be to restart the transfer from 0, but this is desirable.

**Comment by masih** [comment]
Implemented in #147
